// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdlbezzgoxaoiumlsgpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkbGJlenpnb3hhb2l1bWxzZ3BwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMzc3OTcsImV4cCI6MjA3MDgxMzc5N30.lEPJWuWG2z7lsq8bTizeARpvIMeixTrPAnEpG9oOb7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});